### ISSUE TITLE
Running any command fails

### ISSUE THREAD

**Issue by opsydev** [kimmobrunfeldt/concurrently#117]
I am having trouble getting concurrently to run at all. Running any command returns

```
node_modules/concurrently/src/main.js:218
    var lastPrefixColor = _.get(chalk, chalk.gray.dim);
                            ^

TypeError: _.get is not a function
    at run (/path/to/node_modules/concurrently/src/main.js:218:29)
    at main (/path/to/node_modules/concurrently/src/main.js:72:5)
    at Object.<anonymous> (/path/to/node_modules/concurrently/src/main.js:508:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

The only thing I can run is `./node_modules/.bin/concurrently --version`

Concurrenly is installed only in package.json not globally.

Concurrently version 3.5.0
Node v8.2.1
npm 5.3.0
OSX 10.12.6

Am I missing anything?

**Comment by gustavohenke** [comment]
Can you try reinstalling concurrently? It seems like something broke its dependencies chain.

**Comment by opsydev** [comment]
Hey,

Sorry I didn't respond earlier. My GH email notifications were disabled. I found the issue. For some reason my package-lock.json was fixed on an earlier version of stuff. Had to delete the lock file. I had tried running npm upgrade earlier but it looks like it didn't actually upgrade anything.

It's fine now. Thank you for the quick reply.
