### ISSUE TITLE
Nodemon restart with 'rs' not working

### ISSUE THREAD

**Issue by MidnightP** [kimmobrunfeldt/concurrently#121]
Great module!

One issue though it seems.

When I start my create-react-app and express server with:

```concurrently \"react-scripts start\" \"nodemon server/main.js\```

Restarting the server with nodemon by typing `rs` doesn't work anymore. I tried starting concurrently in reversed order bu no avail.

Any ideas?

concurrently: ^3.5.0
nodemon: ^1.11.0

**Comment by gustavohenke** [comment]
Unfortunately, concurrently does nothing to the processes' stdin.
That's why typing `rs` won't work - it's never sent to the nodemon process!

**Comment by SaarLevy** [comment]
I would also have loved to see this feature, but I guess the hassle this module saves is work typing in `Ctrl +c + npm start`

**Comment by MidnightP** [comment]
is worth?

**Comment by Jackclarify** [comment]
@pgraham https://github.com/kimmobrunfeldt/concurrently/pull/128, this pr works without '-r'(--row), `concurrently -k -r "ng build -w -dop=false" "gulp run-dev"`,it throw error: 
```
C:\pj\node_modules\concurrently\src\main.js:305
            target.stdin.write(line);
                        ^

TypeError: Cannot read property 'write' of null
    at Socket.process.stdin.on (C:\pj\node_modules\concurrently\src\main.js:305:25)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at Pipe.onread (net.js:585:20)
npm ERR! code ELIFECYCLE

```
https://github.com/kimmobrunfeldt/concurrently/issues/115, this answer solve my question.

**Comment by demisx** [comment]
I am running the latest 3.6.0 and node 10.4.1. Have this npm script that launches a few watch jobs in parallel:

```sh
$ concurrently --raw 'npm run watch:build' 'npm run watch:apidoc' 'npm run watch:test:unit' 'npm run watch:server'`
```

The watch mode starts fine for all. However typing "rs" to restart nodemon and hitting "Enter" (or simply hitting "Enter") started to crash with the same type of error and leaving npm/node zombie processes behind that I need to kill manually:

```sh
TypeError: Cannot read property 'write' of null
    at ReadStream.process.stdin.on (/Users/dmoore/projects/api/node_modules/concurrently/src/main.js:306:26)
    at ReadStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at ReadStream.Readable.push (_stream_readable.js:219:10)
    at TTY.onread (net.js:635:20)
[dmoore (test-add-condition-to-relation)]$ rsevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at TTY.onread (net.js:656:25)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@0.1.0 watch:server: `nodemon --delay 1000ms './dist/index.js' --watch './dist' --ext 'js'`
npm ERR! Exit status 1
```
