### ISSUE TITLE
Cannot read property 'fromEvent' of undefined

### ISSUE THREAD

**Issue by tgoyer** [kimmobrunfeldt/concurrently#141]
Currently getting this error while trying to run concurrently in an NPM script:
```
/<project path>/node_modules/concurrently/src/main.js:281
            error: Rx.Node.fromEvent(child, 'error'),
                           ^

TypeError: Cannot read property 'fromEvent' of undefined
    at /<project path>/node_modules/concurrently/src/main.js:281:28
    at arrayMap (/<project path>/node_modules/lodash/lodash.js:631:23)
    at Function.map (/<project path>/node_modules/lodash/lodash.js:9546:14)
    at toStreams (/<project path>/node_modules/concurrently/src/main.js:279:14)
    at run (/<project path>/node_modules/concurrently/src/main.js:252:19)
    at main (/<project path>/node_modules/concurrently/src/main.js:72:5)
    at Object.<anonymous> (/<project path>/node_modules/concurrently/src/main.js:512:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```
**node ver:** v8.11.1
**npm ver:** v.6.0.0
**cmd:** `"watch": "npm run build-dev; concurrently -p \"[Task: {name}]\" -n \"TS,SASS,VIEWS\" -c \"yellow.bold,magenta.bold,green.bold\" \"npm run watch-tsc\" \"npm run watch-styles\" \"npm run watch-views\""`

I've confirmed that each of those tasks run separately.

**Comment by tgoyer** [comment]
Disregard.  I uninstalled and then reinstalled.  It's now working.
