### ISSUE TITLE
Combination of lint + test coverage report throws

### ISSUE THREAD

**Issue by nkbt** [kimmobrunfeldt/concurrently#15]
I see it pretty awkward. Same issue for `parallelshell` https://github.com/keithamus/parallelshell/issues/36

```
21:06 $ `npm bin`/concurrent 'eslint .' 'node_modules/.bin/karma start ./karma.conf.js --single-run --reporters coverage' -w
[0] 
[0] fs.js:691
[0]   return binding.lstat(pathModule._makeLong(path));
[0]                  ^
[0] Error: ENOENT, no such file or directory '/Users/nkbt/nkbt/react-component-template/reports/coverage/prettify.js'
[0]     at Object.fs.lstatSync (fs.js:691:18)
[0]     at Object.realpathSync (fs.js:1279:21)
[0]     at executeOnFile (/Users/nkbt/.nvm/v0.10.40/lib/node_modules/eslint/lib/cli-engine.js:559:27)
[0]     at Array.forEach (native)
[0]     at /Users/nkbt/.nvm/v0.10.40/lib/node_modules/eslint/lib/cli-engine.js:626:49
[0]     at Array.forEach (native)
[0]     at CLIEngine.executeOnFiles (/Users/nkbt/.nvm/v0.10.40/lib/node_modules/eslint/lib/cli-engine.js:622:18)
[0]     at Object.cli.execute (/Users/nkbt/.nvm/v0.10.40/lib/node_modules/eslint/lib/cli.js:159:95)
[0]     at Object.<anonymous> (/Users/nkbt/.nvm/v0.10.40/lib/node_modules/eslint/bin/eslint.js:61:20)
[0]     at Module._compile (module.js:456:26)
[0] eslint . exited with code 8
[1] Hash: c026f8c83672b2f634d8
[1] Version: webpack 1.12.2
[1] Time: 5ms
[1] webpack: bundle is now VALID.
[1] webpack: bundle is now INVALID.
[1] Hash: 95583aaf2ae88eb15123
[1] Version: webpack 1.12.2
[1] Time: 1256ms
[1]         Asset    Size  Chunks             Chunk Names
[1] test/index.js  675 kB       0  [emitted]  test/index.js
[1] chunk    {0} test/index.js (test/index.js) 605 kB [rendered]
[1] webpack: bundle is now VALID.
[1] 27 09 2015 21:07:10.642:INFO [karma]: Karma v0.13.10 server started at http://localhost:9876/
[1] 27 09 2015 21:07:10.647:INFO [launcher]: Starting browser PhantomJS
[1] 27 09 2015 21:07:11.492:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket N9E3oUbV-cfUo4UiAAAA with id 78409084
[1] ---------------|----------|----------|----------|----------|----------------|
[1] File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
[1] ---------------|----------|----------|----------|----------|----------------|
[1]  src/          |    88.89 |      100 |       50 |    66.67 |                |
[1]   Component.js |    88.89 |      100 |       50 |    66.67 |              6 |
[1] ---------------|----------|----------|----------|----------|----------------|
[1] All files      |    88.89 |      100 |       50 |    66.67 |                |
[1] ---------------|----------|----------|----------|----------|----------------|
[1] 
[1] node_modules/.bin/karma start ./karma.conf.js --single-run --reporters coverage exited with code 0
```

Node 0.10.40

**Comment by kimmobrunfeldt** [comment]
The error seems to be happening inside eslint code, and it seems to be some file resolve/path problem. Not much I can do to this with this knowledge.

**Comment by nkbt** [comment]
@kimmobrunfeldt all scripts are working properly one by one with or without `concurrently`. Only combination of these two with `concurrently` breaks. If you wish, you can try it with https://github.com/nkbt/react-component-template

**Comment by nkbt** [comment]
Just in case, I tried GNU `parallel` http://www.gnu.org/software/parallel/ and it worked ok

```
✔ ~/nkbt/react-component-template [master|✔] 
23:49 $ echo -ne "npm run lint -s\nnpm run build -s\nnpm run test:cov -s" | parallel
src/Component.js -> lib/Component.js
src/index.js -> lib/index.js
Hash: a64fb6c37360b5188cc3
Version: webpack 1.12.2
Time: 473ms
                          Asset     Size  Chunks             Chunk Names
    react-component-template.js  3.13 kB       0  [emitted]  main
react-component-template.js.map  3.06 kB       0  [emitted]  main
    + 3 hidden modules
Hash: 691877f4066bdd521306
Version: webpack 1.12.2
Time: 1290ms
        Asset       Size  Chunks             Chunk Names
    bundle.js     607 kB       0  [emitted]  main
bundle.js.map     734 kB       0  [emitted]  main
   index.html  185 bytes          [emitted]  
    + 154 hidden modules
Hash: c026f8c83672b2f634d8
Version: webpack 1.12.2
Time: 5ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
Hash: 95583aaf2ae88eb15123
Version: webpack 1.12.2
Time: 1308ms
        Asset    Size  Chunks             Chunk Names
test/index.js  675 kB       0  [emitted]  test/index.js
chunk    {0} test/index.js (test/index.js) 605 kB [rendered]
webpack: bundle is now VALID.
27 09 2015 23:49:51.241:INFO [karma]: Karma v0.13.10 server started at http://localhost:9876/
27 09 2015 23:49:51.245:INFO [launcher]: Starting browser PhantomJS
27 09 2015 23:49:52.090:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket tLhnfsu8nsaS-ZxEAAAA with id 88018931
---------------|----------|----------|----------|----------|----------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------|----------|----------|----------|----------|----------------|
 src/          |    88.89 |      100 |       50 |    66.67 |                |
  Component.js |    88.89 |      100 |       50 |    66.67 |              6 |
---------------|----------|----------|----------|----------|----------------|
All files      |    88.89 |      100 |       50 |    66.67 |                |
---------------|----------|----------|----------|----------|----------------|
```

**Comment by kimmobrunfeldt** [comment]
Ok that's not good. I'm afraid I don't have time to investigate in the near future. If you find the underlying issue, you can comment it to this issue.

It might be simply that the CWD is incorrect when concurrently runs the eslint/karma.

**Comment by nkbt** [comment]
I'll debug it more, seems pretty interesting issue

**Comment by kimmobrunfeldt** [comment]
@nkbt Did you find out what was the underlying issue here?

**Comment by nkbt** [comment]
Somehow I don't have this problem anymore, but what exactly fixed it - not sure. I do not use karma anymore, switched to tape, also updated node, and switched to `parallelshell`. Works pretty well.

It might be also related to some cross-OS env tooling (which used child processes). Now I use `cross-env` which seems to not cause any problems.

So basically I changed my stack quite a bit, and do not have this issue anymore, but did not fix it directly.

**Comment by kimmobrunfeldt** [comment]
Closing because of inactivity.
