### ISSUE TITLE
Error in forever

### ISSUE THREAD

**Issue by isairz** [kimmobrunfeldt/concurrently#17]
I want to use concurrent with forever. but that occur errors.

package.json
```
scripts: {
  "start": concurrent --kill-others \"npm run start-prod\" \"npm run start-prod-api\",
  ...
}
```

```
$ forever -c "npm run start" ./
```

**Comment by kimmobrunfeldt** [comment]
Could you post the full stack trace or output of the error?

**Comment by kimmobrunfeldt** [comment]
Closed because of lack of error details

**Comment by manubamba** [comment]
I have a similar problem. Here's the stacktrace.

`> react-redux-universal-hot-example@0.9.0 start /Users/manu/Work/Projects/markt/reduxEx
> concurrently --kill-others "npm run start-prod" "npm run start-prod-api" "/Users/manu/Work/Projects/markt/reduxEx/"

Error occured when executing command: /Users/manu/Work/Projects/markt/reduxEx/
Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:362:9)
    at spawn (/Users/manu/Work/Projects/markt/reduxEx/node_modules/cross-spawn/index.js:87:19)
    at /Users/manu/Work/Projects/markt/reduxEx/node_modules/concurrently/src/main.js:182:21
    at arrayMap (/Users/manu/Work/Projects/markt/reduxEx/node_modules/concurrently/node_modules/lodash/index.js:1377:25)
    at Function.map (/Users/manu/Work/Projects/markt/reduxEx/node_modules/concurrently/node_modules/lodash/index.js:5891:14)
    at run (/Users/manu/Work/Projects/markt/reduxEx/node_modules/concurrently/src/main.js:172:22)
    at main (/Users/manu/Work/Projects/markt/reduxEx/node_modules/concurrently/src/main.js:50:5)
    at Object.<anonymous> (/Users/manu/Work/Projects/markt/reduxEx/node_modules/concurrently/src/main.js:390:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/manu/.nvm/v5.5.0/bin/node" "/Users/manu/.nvm/v5.5.0/bin/npm" "run" "start" "/Users/manu/Work/Projects/markt/reduxEx/"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-redux-universal-hot-example@0.9.0 start: `concurrently --kill-others "npm run start-prod" "npm run start-prod-api" "/Users/manu/Work/Projects/markt/reduxEx/"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-universal-hot-example@0.9.0 start script 'concurrently --kill-others "npm run start-prod" "npm run start-prod-api" "/Users/manu/Work/Projects/markt/reduxEx/"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-universal-hot-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others "npm run start-prod" "npm run start-prod-api" "/Users/manu/Work/Projects/markt/reduxEx/"
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-universal-hot-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manu/Work/Projects/markt/reduxEx/npm-debug.log
error: Forever detected script exited with code: 1`
