### ISSUE TITLE
Errors with concurrently

### ISSUE THREAD

**Issue by viganzeqiri** [kimmobrunfeldt/concurrently#174]
I am trying to run two scripts but it fails
they work when i run them alone.

PS C:\Users\Lenovo\Desktop\MERN\shopingList> npm run dev

> shopinglist@1.0.0 dev C:\Users\Lenovo\Desktop\MERN\shopingList
> concurrently "npm run server" "npm run client"

 Error occured when executing command: npm run clientError: spawn cmd.exe ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
     at onErrorNT (internal/child_process.js:406:16)
     at process._tickCallback (internal/process/next_tick.js:63:19)
     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
     at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)Error occured when executing command: npm run clientError: spawn cmd.exe ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
     at onErrorNT (internal/child_process.js:406:16)
     at process._tickCallback (internal/process/next_tick.js:63:19)
     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
     at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)npm run client exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopinglist@1.0.0 dev: `concurrently "npm run server" "npm run client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopinglist@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output
above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-10-24T04_26_26_659Z-debug.log

**Comment by gustavohenke** [comment]
So did you figure it out by yourself?

**Comment by viganzeqiri** [comment]
yes, i forgot to change the port for node.js script

Thanks

**Comment by viganzeqiri** [comment]
I dont know why the error was so unclear
