### ISSUE TITLE
Run the same command in multiple directories

### ISSUE THREAD

**Issue by heruan** [kimmobrunfeldt/concurrently#54]
I'm used to run the same command on multiple directories, and I'd like to switch to `concurrently` to take advantage of its nice output. How can achieve this?

Currently I'm doing this, without `concurrently`:
```javascript
var child = require("child_process");
var directories = [ "foo", "bar", "baz" ];
directories.forEach(dir => child.spawn("ncu", [ "-a" ], { cwd: dir }));
```

**Comment by kimmobrunfeldt** [comment]
Would this work for you: `concurrently "cd foo && ncu -a" "cd bar && ncu -a" "cd baz && ncu -a"`?

**Comment by kimmobrunfeldt** [comment]
Closing because of inactivity. The above solution should work.

**Comment by Alex0007** [comment]
@kimmobrunfeldt 
Linux
Node 7.9.0
```
$ concurrently "cd ./server && npm run dev" "npm run watch:client" 
 Error occured when executing command: cd ./server && npm run dev
 Error: spawn cd ENOENT
     at exports._errnoException (util.js:1050:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:607:11)
     at run (bootstrap_node.js:423:7)
     at startup (bootstrap_node.js:147:9)
     at bootstrap_node.js:538:3
```
